extends: cheminfo

env:
  browser: true
  es6: true
  jest: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  array-bracket-spacing: [error, always]
  array-callback-return: warn
  brace-style: off
  camelcase: warn
  consistent-return: off
  curly: off
  default-case: warn
  eqeqeq: off
  indent: off
  no-compare-neg-zero: warn
  no-console: off
  no-cond-assign: warn
  no-redeclare: off
  no-unreachable: warn
  no-unused-expressions: warn
  no-unused-vars: warn
  one-var: off
  space-in-parens: [error, always]
  space-before-function-paren: off # conflicts with beautifier
  valid-jsdoc: off
  space-unary-ops: off
  one-var-declaration-per-line: off
  no-empty-function: off
  dot-location: off
  quote-props: off
  no-prototype-builtins: off
  no-dupe-class-members: warn
  no-case-declarations: warn
  eol-last: off
  no-throw-literal: warn
  no-sequences: off
  no-return-assign: off
  no-loop-func: warn
  no-self-compare: warn
  no-new: warn
  computed-property-spacing: off
  padded-blocks: off
  array-bracket-newline: off
  symbol-description: warn
  object-curly-spacing: off
  spaced-comment: off
  prefer-rest-params: off
  template-curly-spacing: off
  handle-callback-err: off
  no-useless-constructor: off
  prefer-spread: off
  no-tabs: warn
  no-irregular-whitespace: warn
